const UpcomingMoviesActionTypes = {
  FETCH_UPCOMING_MOVIES: "FETCH_UPCOMING_MOVIES",
  FETCH_UPCOMING_REQUEST: "FETCH_UPCOMING_REQUEST",
  FETCH_UPCOMING_SUCCESS: "FETCH_UPCOMING_SUCCESS",
  FETCH_UPCOMING_FAILURE: "FETCH_UPCOMING_FAILURE",
};

export default UpcomingMoviesActionTypes;
