const SearchMoviesActionTypes = {
  FETCH_SEARCH_MOVIES: "FETCH_SEARCH_MOVIES",
  FETCH_SEARCH_REQUEST: "FETCH_SEARCH_REQUEST",
  FETCH_SEARCH_SUCCESS: "FETCH_SEARCH_SUCCESS",
  FETCH_SEARCH_FAILURE: "FETCH_SEARCH_FAILURE",
};

export default SearchMoviesActionTypes;
