const PopularMoviesActionTypes = {
  FETCH_POPULAR_MOVIES: "FETCH_POPULAR_MOVIES",
  FETCH_POPULAR_REQUEST: "FETCH_POPULAR_REQUEST",
  FETCH_POPULAR_SUCCESS: "FETCH_POPULAR_SUCCESS",
  FETCH_POPULAR_FAILURE: "FETCH_POPULAR_FAILURE",
};

export default PopularMoviesActionTypes;
